In [1]:
import tensorflow as tf
import os
import sys
sys.path.append('./')

from model_stream import DECNN_SMALL,Spon_SMALL
import numpy as np
import soundfile as sf
import librosa
#import matplotlib.pyplot as plt
#import librosa.display
from scipy import signal
from data_process.data_process import *


def predict_multi(path,result_path):
    all_wav_file = find_files(path,dtype='wav')
    for i in all_wav_file:
        wav = librosa.load(i,sr = 16000,dtype='float32')[0]
        print(np.shape(np.array([wav])))

        if not os.path.exists(result_path+'/DECNN'):
            os.makedirs(result_path+'/DECNN')
        if not os.path.exists(result_path + '/SPON'):
            os.makedirs(result_path + '/SPON')
        if not os.path.exists(result_path + '/DECNN-SPON'):
            os.makedirs(result_path + '/DECNN-SPON')


        data = model_DECNN.predict(np.array([wav]))
        save_path = os.path.join(result_path+'/DECNN', os.path.basename(i)[:-4] + '_DECNN.wav')
        sf.write(save_path, data[0], sr)

        DATA = model_SPON.predict(data)
        save_path = os.path.join(result_path + '/DECNN-SPON', os.path.basename(i)[:-4] + 'DECNN_SPON_MIN.wav')
        sf.write(save_path, DATA[0], sr)

        DD = model_SPON.predict(np.array([wav]))
        save_path = os.path.join(result_path + '/SPON', os.path.basename(i)[:-4] + '_SPON_MIN.wav')
        sf.write(save_path, DD[0], sr)

def test():
    model_DECNN = DECNN_SMALL(batch_size=1,gain=12)
    # model_SPON = Spon_DCCRN_small(batch_size=1)
    model_SPON = Spon_SMALL(batch_size=1)
    # model_SPON = Spon_DCCRN(batch_size=1)


    model_DECNN.load_weights("./DECNN_SMALL_hann.h5")
    model_SPON.load_weights("./SPON_SMALL_sin.h5")

    # model_DECNN.load_weights(
    #      "/home/spon/hgm/spon_speech_enhance/Spon_speech_enhance_Mag_Mask/model_weight_small/DECNN_SMALL_0530_lossFunction_si_snr_mag_hann/model_06_-12.030354.h5")
    # model_SPON.load_weights(
    #     '/home/spon/hgm/spon_speech_enhance/Spon_speech_enhance_Mag_Mask/model_weight_small/Spon_SMALL_0530_lossFunction_si_snr_hann/model_06_-14.353806.h5')

    # model_SPON.load_weights("/home/spon/hgm/spon_speech_enhance/Spon_speech_enhance_Mag_Mask/model_weight/Spon_Mag2Mag_ToConcerter_MIN_0323_snr_0-20/Spon_Mag2Mag_ToConcerter_MIN_0323_snr_0-20model_10_-20.065332.h5")
    return model_DECNN, model_SPON


2023-06-29 09:27:33.542891: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-29 09:27:33.576039: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-29 09:27:33.576455: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-29 09:27:34.253097: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
model_DECNN, model_SPON = test()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(1, None)]          0           []                               
                                                                                                  
 lambda (Lambda)                [(1, None, 257),     0           ['input_1[0][0]']                
                                 (1, None, 257)]                                                  
                                                                                                  
 lambda_1 (Lambda)              (1, None, 257, 1)    0           ['lambda[0][0]']                 
                                                                                                  
 layer_normalization (LayerNorm  (1, None, 257, 1)   514         ['lambda_1[0][0]']           

 conv2d_transpose_3 (Conv2DTran  (1, None, 128, 4)   96          ['p_re_lu_7[0][0]']              
 spose)                                                                                           
                                                                                                  
 tf.__operators__.getitem (Slic  (1, None, 127, 4)   0           ['conv2d_transpose_3[0][0]']     
 ingOpLambda)                                                                                     
                                                                                                  
 batch_normalization_8 (BatchNo  (1, None, 127, 4)   16          ['tf.__operators__.getitem[0][0]'
 rmalization)                                                    ]                                
                                                                                                  
 p_re_lu_8 (PReLU)              (1, None, 127, 4)    4           ['batch_normalization_8[0][0]']  
          

2023-06-29 09:27:37.507006: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-06-29 09:27:37.508503: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-06-29 09:27:37.509364: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You mus

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_2 (InputLayer)           [(1, None)]          0           []                               
                                                                                                  
 lambda_4 (Lambda)              [(1, None, 257),     0           ['input_2[0][0]']                
                                 (1, None, 257)]                                                  
                                                                                                  
 lambda_5 (Lambda)              (1, None, 257, 1)    0           ['lambda_4[0][0]']               
                                                                                                  
 lambda_6 (Lambda)              (1, None, 257, 1)    0           ['lambda_4[0][1]']         

                                                                                                  
 conv2d_transpose_7 (Conv2DTran  (1, None, 64, 4)    192         ['p_re_lu_15[0][0]']             
 spose)                                                                                           
                                                                                                  
 batch_normalization_16 (BatchN  (1, None, 64, 4)    16          ['conv2d_transpose_7[0][0]']     
 ormalization)                                                                                    
                                                                                                  
 p_re_lu_16 (PReLU)             (1, None, 64, 4)     4           ['batch_normalization_16[0][0]'] 
                                                                                                  
 conv2d_transpose_8 (Conv2DTran  (1, None, 128, 4)   96          ['p_re_lu_16[0][0]']             
 spose)   

In [3]:
import tensorflow.keras
from tensorflow.keras.models import Model
model = model_DECNN
# 创建一个新的模型，输出是每一层的输出
layer_outputs = [layer.output for layer in model.layers]
activation_model = Model(inputs=model.input, outputs=layer_outputs)
index = 0
for layer in model.layers:
    print("Layer Index", index)
    print("Layer name:", layer.name)
    print("Input shape:", layer.input_shape)
    print("Output shape:", layer.output_shape)
    weights = layer.get_weights()
    #print(weights.name)
    index = index + 1
    if len(weights) > 0:
        for i, w in enumerate(weights):
            print("Weight", i+1, "Weight Shape", w.shape)
            print(w)

# 输入数据进行推理
wav = librosa.load('录音仿真音频.wav', sr = 16000,dtype='float32')[0]
wav = wav[0:768]
input_data = np.array([wav])
outputs = activation_model.predict(input_data)

layer_output_list = []
# 输出每一层的结果
for layer_output in outputs:
    #print(layer_output)
    layer_output_list.append(layer_output)

Layer Index 0
Layer name: input_1
Input shape: [(1, None)]
Output shape: [(1, None)]
Layer Index 1
Layer name: lambda
Input shape: (1, None)
Output shape: [(1, None, 257), (1, None, 257)]
Layer Index 2
Layer name: lambda_1
Input shape: (1, None, 257)
Output shape: (1, None, 257, 1)
Layer Index 3
Layer name: layer_normalization
Input shape: (1, None, 257, 1)
Output shape: (1, None, 257, 1)
Weight 1 Weight Shape (1, 257)
[[ 0.3676207   0.51941574  3.416638    1.0768127   1.8263371   0.27162385
   0.8956034   0.43241858  0.6052129   0.28182352  0.92860234  0.33942163
   0.7774073   0.7090095   0.73540866  0.60461295  0.79360676  0.89500344
   1.0174029   1.0840139   1.102617    1.1776295   1.0942156   0.92200255
   1.0288048   1.1260209   1.0702116   1.036006    1.0390065   0.92800236
   0.9304023   0.7138094   0.9106029   0.8998033   1.0516086   1.1602266
   0.96460116  0.92800236  0.9658011   0.7654077   0.8908036   0.95920134
   1.0048008   0.9304023   0.8962034   1.0108018   1.1200199

Weight 1 Weight Shape (4,)
[1.3246539 0.4534179 1.1680279 0.9886004]
Weight 2 Weight Shape (4,)
[ 0.5231928   0.05400008 -0.01260001 -0.15660015]
Weight 3 Weight Shape (4,)
[ 1.277896    0.24699675 -0.8735486  -0.29818654]
Weight 4 Weight Shape (4,)
[8.742264  0.7671649 2.1420505 0.7980726]
Layer Index 6
Layer name: p_re_lu
Input shape: (1, None, 127, 4)
Output shape: (1, None, 127, 4)
Weight 1 Weight Shape (1, 1, 4)
[[[ 0.7655849  -1.5366663  -0.14339994 -0.30180004]]]
Layer Index 7
Layer name: tf.compat.v1.pad
Input shape: (1, None, 127, 4)
Output shape: (1, None, 129, 4)
Layer Index 8
Layer name: conv2d_1
Input shape: (1, None, 129, 4)
Output shape: (1, None, 64, 4)
Weight 1 Weight Shape (2, 3, 4, 4)
[[[[-0.31265575  0.4051838   0.01759322 -0.13724253]
   [ 0.12310547 -0.12089078  0.03863041 -0.20579198]
   [ 0.22180122  0.13981599 -0.0943203  -0.07348329]
   [ 0.15354872 -0.45289475 -0.07981374 -0.38585162]]

  [[ 0.08338176 -0.7668813   0.27110702 -0.40209478]
   [ 0.21347202 -0.0

Weight 1 Weight Shape (8,)
[0.8992033  1.0114019  1.193232   0.75460804 0.8656044  0.6604111
 1.1590264  0.5596144 ]
Weight 2 Weight Shape (8,)
[1.2720224  0.40619662 0.23220146 2.3652587  0.19620083 0.8081835
 0.13499981 0.34979847]
Weight 3 Weight Shape (8,)
[-0.70617574  1.2047591   0.9123609  -0.78222847 -0.5175763  -3.0701234
 -0.8873588   0.7140026 ]
Weight 4 Weight Shape (8,)
[0.31411973 1.9858658  0.9430363  0.3390783  0.43455154 0.3730385
 1.0309002  0.30371824]
Layer Index 18
Layer name: p_re_lu_3
Input shape: (1, None, 32, 8)
Output shape: (1, None, 32, 8)
Weight 1 Weight Shape (1, 1, 8)
[[[ 0.39599696  0.39059713  1.3872415   0.4625948  -0.18060055
    0.77218467  0.9839778  -0.04560003]]]
Layer Index 19
Layer name: tf.compat.v1.pad_3
Input shape: (1, None, 32, 8)
Output shape: (1, None, 34, 8)
Layer Index 20
Layer name: conv2d_4
Input shape: (1, None, 34, 8)
Output shape: (1, None, 32, 8)
Weight 1 Weight Shape (2, 3, 8, 8)
[[[[ 0.3806132  -0.01154603 -0.01605217 -0.4270939

Weight 1 Weight Shape (8,)
[0.7612078  0.86140454 0.9850005  0.9904003  0.93760204 0.72100914
 1.3096514  0.68381035]
Weight 2 Weight Shape (8,)
[ 1.0481852  -0.0654001  -0.69298726  0.6437889  -0.25560156  0.46439472
  0.10859976  1.2222141 ]
Weight 3 Weight Shape (8,)
[-0.99265176  1.3012967  -2.6339324   2.6079829  -1.7199817  -0.1976198
  2.1778245   0.3955885 ]
Weight 4 Weight Shape (8,)
[0.7469635  1.6035391  2.3846352  0.94912523 0.9724061  1.6506417
 1.6066562  1.0848423 ]
Layer Index 25
Layer name: p_re_lu_5
Input shape: (1, None, 32, 8)
Output shape: (1, None, 32, 8)
Weight 1 Weight Shape (1, 1, 8)
[[[-0.06180012  0.0366      0.5729912   0.48419407  0.41759625
   -0.02580001  0.823783    0.27000108]]]
Layer Index 26
Layer name: conv2d_transpose_1
Input shape: (1, None, 32, 8)
Output shape: (1, None, 32, 8)
Weight 1 Weight Shape (2, 3, 8, 8)
[[[[ 3.09763830e-02 -2.00109914e-01  4.21398953e-02 -2.47964598e-02
     2.64035732e-01  1.85563900e-02  1.07617229e-02  2.41588816e-01]


1/1 [==============================] - 1s 1s/step


In [4]:
print(layer_output_list[3])

[[[[-1.93651676e+00]
   [ 5.38990831e+00]
   [ 8.44402313e+00]
   [ 1.20324886e+00]
   [ 5.37475014e+00]
   [-4.24275875e-01]
   [ 2.58185291e+00]
   [ 4.08121634e+00]
   [ 2.91647673e+00]
   [ 8.15168321e-02]
   [-6.02915943e-01]
   [ 4.04671907e-01]
   [-7.79692888e-01]
   [ 8.00025821e-01]
   [ 8.03025961e-01]
   [-3.35303396e-01]
   [ 1.00189865e-01]
   [ 1.46247792e+00]
   [-4.81511116e-01]
   [-2.98881263e-01]
   [-4.59901512e-01]
   [ 8.21957290e-01]
   [ 2.18683124e-01]
   [-1.33239806e-01]
   [-3.16041708e-01]
   [ 1.11149561e+00]
   [ 1.11020589e+00]
   [ 2.38997102e+00]
   [ 3.64470339e+00]
   [ 1.36741543e+00]
   [ 3.34421307e-01]
   [ 1.87062263e-01]
   [ 3.84910285e-01]
   [ 1.50092947e+00]
   [ 2.56308055e+00]
   [ 5.17159998e-01]
   [ 1.10882246e+00]
   [ 2.72792041e-01]
   [ 2.15882206e+00]
   [-8.54940116e-02]
   [ 9.15296435e-01]
   [ 4.47021984e-02]
   [-3.25047672e-02]
   [ 1.50395840e-01]
   [ 1.85060954e+00]
   [ 1.88181639e+00]
   [-7.67342448e-02]
   [ 1.057522

In [5]:
print(layer_output_list[3].shape)



(1, 2, 257, 1)


In [53]:
print(layer_output_list[19].shape)# 11 ok p_relu_1  12 前4个误差  16 wan quan bu zheng que conv_3
print(layer_output_list[19])

(1, 2, 34, 8)
[[[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
     0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]
   [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
     0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]
   [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
     0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]
   [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
     0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]
   [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
     0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]
   [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
     0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]
   [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
     0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]
   [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
     0.0000000e+00 

In [7]:
import tensorflow as tf



def save_weights_as_binary(model, filepath):
    weights = []
    layer_names = []
    layer_types = []
    weight_nums = []
    weight_shapes = []
    count = 0
    for layer in model.layers:
        layer_names.append(layer.name)
        layer_types.append(layer.__class__.__name__)
        weights.append(layer.get_weights())
        weight_nums.append(len(weights[-1]))
        #print(len(weights[-1]))
        weight_shapes.append([w.shape for w in weights[-1]])

    with open(filepath, 'wb') as f:
        # 写入层数量
        f.write(len(layer_names).to_bytes(4, byteorder='little'))
        

        for name, typ, num, shapes, weight_group in zip(layer_names, layer_types, weight_nums, weight_shapes, weights):
            # 写入层名长度和层名
            name_len = len(name)
            f.write(name_len.to_bytes(4, byteorder='little'))
            f.write(name.encode())

            # 写入层类型长度和层类型
            typ_len = len(typ)
            f.write(typ_len.to_bytes(4, byteorder='little'))
            f.write(typ.encode())

            # 写入权重数量
            f.write(num.to_bytes(4, byteorder='little'))

            # 写入权重形状
            for shape in shapes:
                shape_len = len(shape)
                f.write(shape_len.to_bytes(4, byteorder='little'))
                for dim in shape:
                    f.write(dim.to_bytes(4, byteorder='little'))

            # 写入权重
            #for weight in weight_group:
                #f.write(weight.tobytes())


# 使用示例
#model = tf.keras.applications.MobileNetV2()
save_weights_as_binary(model, 'weights.bin')


In [8]:
import tensorflow as tf
import numpy as np

def save_weights_as_binary(model, filepath):
    weights = []
    layer_names = []
    layer_types = []
    weight_nums = []
    weight_shapes = []

    for layer in model.layers:
        layer_names.append(layer.name)
        layer_types.append(layer.__class__.__name__)
        weights.append(layer.get_weights())
        weight_nums.append(len(weights[-1]))
        weight_shapes.append([w.shape for w in weights[-1]])
        
    with open(filepath, 'wb') as f:
        # 写入层数量
        f.write(len(layer_names).to_bytes(4, byteorder='little'))

        for name, typ, num, shapes, weight_group in zip(layer_names, layer_types, weight_nums, weight_shapes, weights):
            # 写入层名长度和层名
            name_len = len(name)
            f.write(name_len.to_bytes(4, byteorder='little'))
            f.write(name.encode())

            # 写入层类型长度和层类型
            typ_len = len(typ)
            f.write(typ_len.to_bytes(4, byteorder='little'))
            f.write(typ.encode())

            # 写入权重数量
            f.write(num.to_bytes(4, byteorder='little'))

            # 写入权重形状
            for shape in shapes:
                shape_len = len(shape)
                f.write(shape_len.to_bytes(4, byteorder='little'))
                for dim in shape:
                    f.write(dim.to_bytes(4, byteorder='little'))
            #f.write(shape_len.to_bytes(4, byteorder='little'))
            
            
            
            # 写入权重
            for weight in weight_group:
                weight_bytes = np.asarray(weight, dtype=np.float32).tobytes()
                f.write(weight_bytes)



# 使用示例
#model = tf.keras.applications.MobileNetV2()
save_weights_as_binary(model, 'weights.bin')


In [9]:
import numpy as np
import tensorflow as tf

def load_weights_from_binary(model, filepath):
    with open(filepath, 'rb') as f:
        # 读取层数量
        num_layers = int.from_bytes(f.read(4), byteorder='little')

        for _ in range(num_layers):
            # 读取层名长度和层名
            name_len = int.from_bytes(f.read(4), byteorder='little')
            name = f.read(name_len).decode()

            # 读取层类型长度和层类型
            typ_len = int.from_bytes(f.read(4), byteorder='little')
            typ = f.read(typ_len).decode()

            # 读取权重数量
            num_weights = int.from_bytes(f.read(4), byteorder='little')

            # 读取权重形状
            shapes = []
            for _ in range(num_weights):
                shape_len = int.from_bytes(f.read(4), byteorder='little')
                shape = []
                for _ in range(shape_len):
                    dim = int.from_bytes(f.read(4), byteorder='little')
                    shape.append(dim)
                shapes.append(shape)

            # 读取权重
            weights = []
            for shape in shapes:
                weight_bytes_len = int.from_bytes(f.read(4), byteorder='little')
                weight_bytes = f.read(weight_bytes_len)
                weight_flat = np.frombuffer(weight_bytes, dtype=np.float32)
                weight = np.reshape(weight_flat, shape)
                print(weight)
                weights.append(weight)
            
            # 设置模型权重
            #layer = model.get_layer(name)
            #layer.set_weights(weights)

# 使用示例
#model = tf.keras.applications.MobileNetV2()
load_weights_from_binary(model, 'weights.bin')

ValueError: buffer size must be a multiple of element size